export const LOADING_PRODUCT_DATA = "LOADING_PRODUCT_DATA";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";

//Misc Data
export const LOADING_MISC_DATA = "LOADING_MISC_DATA";
export const GET_WEEKLY_YIELD_DATA = "GET_WEEKLY_YIELD_DATA";
export const GET_UPCOMING_PROD_DATA = "GET_UPCOMING_PROD_DATA";

export const SEARCH_USERS = "SEARCH_USERS";
export const SET_USERS = "SET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
//User Data
export const SET_USER = "SET_USER";
export const UPDATE_USER_IMAGE = "UPDATE_USER_IMAGE";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const SET_USER_INFORMATION = "SET_USER_INFORMATION";
export const SET_USER_IMAGE = "SET_USER_IMAGE";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_USER = "LOADING_USER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Task reducer
export const SET_TASKS = "SET_TASKS";
export const FETCH_DATA = "FETCH_DATA";
export const CREATE_TASKS = "CREATE_TASKS";
export const CREATE_TASKS_LOADING = "CREATE_TASKS_LOADING";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_TASK_ERRORS = "SET_TASK_ERRORS";
export const CLEAR_TASK_ERRORS = "CLEAR_TASK_ERRORS";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const COMPLETE_TASK_LOADING = "COMPLETE_TASK_LOADING";
export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING";
//Event reducer
export const FETCH_EVENT_DATA = "FETCH_EVENT_DATA";
export const GET_EVENTS = "GET_EVENTS";
export const CREATE_EVENT = "CLEAR_ERRORS";
export const UPDATE_EVENT = "CLEAR_ERRORS";
export const DELETE_EVENT = "DELETE_EVENT";
export const SET_EVENT_ERRORS = "SET_EVENT_ERRORS";
export const CLEAR_EVENT_ERRORS = "CLEAR_EVENT_ERRORS";
