export const LOADING_PRODUCT_DATA = "LOADING_PRODUCT_DATA";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";

//Misc Data
export const LOADING_MISC_DATA = "LOADING_MISC_DATA";
export const GET_WEEKLY_YIELD_DATA = "GET_WEEKLY_YIELD_DATA";
export const GET_UPCOMING_PROD_DATA = "GET_UPCOMING_PROD_DATA";

//User Data
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_USER = "LOADING_USER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
