//By ProductSET_PRODUCT_DATA\
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const LOADING_PRODUCT_DATA = "LOADING_PRODUCT_DATA";
export const GET_PRODUCT_DATA_ALL = "GET_PRODUCT_DATA_ALL";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_PRODUCT_DATA_START = "GET_PRODUCT_DATA_START";
export const GET_PRODUCT_DATA_COAT = "GET_PRODUCT_DATA_COAT";
export const GET_PRODUCT_DATA_DICE = "GET_PRODUCT_DATA_DICE";
export const GET_PRODUCT_DATA_ETCH = "GET_PRODUCT_DATA_ETCH";
export const GET_PRODUCT_DATA_GRIND = "GET_PRODUCT_DATA_GRIND";
export const GET_PRODUCT_DATA_POLISH = "GET_PRODUCT_DATA_POLISH";

//Misc Data
export const LOADING_MISC_DATA = "LOADING_MISC_DATA";
export const GET_WEEKLY_YIELD_DATA = "GET_WEEKLY_YIELD_DATA";
export const GET_UPCOMING_PROD_DATA = "GET_UPCOMING_PROD_DATA";
export const GET_USER_DATA_ALL = "GET_USER_DATA_ALL";
export const GET_USER_DATA = "GET_USER_DATA";

//Defect Summaries
export const LOADING_DEFECT_DATA = "LOADING_DEFECT_DATA";
//By Product
export const DICE_DEFECT_BY_PROD = "DICE_DEFECT_BY_PROD";
export const GRIND_DEFECT_BY_PROD = "GRIND_DEFECT_BY_PROD";
export const POLISH_DEFECT_BY_PROD = "POLISH_DEFECT_BY_PROD";
export const START_DEFECT_BY_PROD = "START_DEFECT_BY_PROD";
export const COAT_DEFECT_BY_PROD = "COAT_DEFECT_BY_PROD";
export const ETCH_DEFECT_BY_PROD = "ETCH_DEFECT_BY_PROD";
//All
export const DICE_DEFECT_SUM = "DICE_DEFECT_SUM";
export const GRIND_DEFECT_SUM = "GRIND_DEFECT_SUM";
export const POLISH_DEFECT_SUM = "POLISH_DEFECT_SUM";
export const START_DEFECT_SUM = "START_DEFECT_SUM";
export const COAT_DEFECT_SUM = "COAT_DEFECT_SUM";
export const ETCH_DEFECT_SUM = "ETCH_DEFECT_SUM";

//Product Comment
export const LOADING_COMMENT_DATA = "LOADING_COMMENT_DATA";
export const GET_PRODUCT_COMMENT_ALL = "GET_PRODUCT_COMMENT_DATA_ALL";
export const GET_PRODUCT_COMMENT = "GET_PRODUCT_COMMENT";
export const POST_PRODUCT_COMMENT = "POST_PRODUCT_COMMENT";
export const UPDATE_PRODUCT_COMMENT = "UPDATE_PRODUCT_COMMENT";
export const DELETE_PRODUCT_COMMENT = "DELETE_PRODUCT_COMMENT";

//ToolData
export const LOADING_TOOL_DATA = "LOADING_TOOL_DATA";
export const GET_TOOL_DATA_ALL = "GET_TOOL_DATA_ALL";
export const GET_TOOL_DATA = "GET_TOOL_DATA";
export const POST_TOOL_DATA = "POST_TOOL_DATA";
export const UPDATE_TOOL_DATA = "UPDATE_TOOL_DATA";
export const DELETE_TOOL_DATA = "DELETE_TOOL_DATA";
